### ISSUE TITLE
provide docker image for HeFQUIN

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/HeFQUIN#339]
This issue is about creating a docker image as a wrapper for running HeFQUIN.

**Comment by keski** [comment]
A docker image can now be built by pulling from the HeFQUIN repo. An optional argument (`TAG`) can be provided to build a specific HeFQUIN release, otherwise the latest version is used. At present, the image is built from #338 but this will be switched to main before PR.

## Example usage

```bash
$ docker-compose build
$ docker-compose up
```

## Docker compose file
```yml
ersion: '3.8'

services:
  hefquin:
    build:
      context: .
      args:
        TAG: docker-test # (optional) build from a specific release tag
    ports:
      - "8080:8080"
    volumes: # (optional) mount a custom config.properties files
     # Mount a custom config.properties file and add config files
     - ./example/config.properties:/usr/local/tomcat/webapps/ROOT/config.properties
     - ./example/ExampleEngineConf.ttl:/usr/local/tomcat/webapps/ROOT/ExampleEngineConf.ttl
     - ./example/ExampleFedConf.ttl:/usr/local/tomcat/webapps/ROOT/ExampleFedConf.ttl
```
