### ISSUE TITLE
Trigger maven.yml on push to main

### ISSUE THREAD

**Issue by keski** [LiUSemWeb/HeFQUIN#366]
Currently, any push to the repo (regardless of branch) results in the `maven.yml` workflow being triggered. I would suggest that we restrict this to pushes to the `main` branch. That is:

```yml
on: [push]
```

should be changed to:

```yml
on:
  push:
    branches:
      - main
```

This would speed up the build process during development a bit.

@hartig
